apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: rp2
spec:
  selector:
    matchLabels:
      app: rp2
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: rp2
        tier: frontend
        track: stable
    spec:
      containers:
      - name: rp2
        image: "robertmozeika/rp2:latest"