apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  selector:
    app: monorift
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc5
spec:
  selector:
    app: monorift
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 27017
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: monorift
  replicas: 1
  template:
    metadata:
      labels:
        app: monorift
    spec:
      containers:
      - name: mongo
        image: "mongo:latest"
        command: ['sh', '-c', 'until nslookup db-svc; do echo waiting for mydb; sleep 2; done;']
        ports:
        - containerPort: 27017

      - name: rp2
        image: "robertmozeika/rp2:latest"
        command: ['sh', '-c', 'until nslookup db-svc; do echo waiting for mydb; sleep 2; done;']
        ports:
        - containerPort: 8080
      