apiVersion: v1
kind: Service
metadata:
  name: duce
spec:
  selector:
    app: hello
    tier: duce
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duce
spec:
  selector:
    matchLabels:
      app: hello
      tier: duce
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: duce
        track: stable
    spec:
      containers:
      - name: rp2
        image: "robertmozeika/rp2:latest"