version: "3"
services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "7667:80"
    expose:
      - "80"
    volumes:
      # - web-root:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
    depends_on:
      - node
    links:
      - node
  node:
    #network_mode: host
    image: "rp2:latest"


    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "db-svc:27017", "--", "npm", "start"]
    # command: "npm start"
    depends_on: 
      - db-svc
    links: 
      - db-svc
  db-svc:
    #network_mode: host
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017


    